services:
  unbound:
    image: "mvance/unbound:1.18.0"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      wg-easy:
        ipv4_address: 10.8.1.4
    healthcheck:
      test: ["CMD", "dig", "-p", "53", "dnssec.works", "@127.0.0.1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  wg-easy:
    image: "weejewel/wg-easy:10"
    container_name: wg-easy
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=<SERVER_IP>

      # ⚠️ Change the Web UI Password:
      - PASSWORD=<WGEASY_PASSWORD>

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    dns:
      - 10.8.1.3 # pihole
      - 10.8.1.4 # unbound
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  pihole:
    image: "pihole/pihole:2023.02.2"
    depends_on: [ unbound ]
    container_name: pihole
    hostname: pihole
    dns:
      - 10.8.1.4 # unbound
      - 127.0.0.1
    environment:
      # ⚠️ Change the Web UI Password:
      WEBPASSWORD: <PIHOLE_PASSWORD>
      TZ: "Europe/Moscow"
      ServerIP: 10.8.1.3
      DNS1: 10.8.1.4
      DNS2: 10.8.1.4
      CACHE_SIZE: 0
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
    cpus: "0.8"

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
